const TeamNames = [
    "Virginia",
    "Cincinnati",
    "Tennessee",
    "Arizona",
    "Kentucky",
    "Miami (FL)",
    "Nevada",
    "Creighton",
    "Kansas State",
    "Texas",
    "Loyola-Chicago",
    "Davidson",
    "Buffalo",
    "Wright State",
    "Georgia State",
    "Maryland-Baltimore Co.",
    "Xavier",
    "North Carolina",
    "Michigan",
    "Gonzaga",
    "Ohio State",
    "Houston",
    "Texas A&M",
    "Missouri",
    "Florida State",
    "Providence",
    "San Diego State",
    "South Dakota State",
    "N. Caroline-Greensboro",
    "Montana",
    "Lipscomb",
    "N. Carolina-Central/Texas So.",
    "Villanova",
    "Purdue",
    "Texas Tech",
    "Wichita State",
    "West Virginia",
    "Florida",
    "Arkansas",
    "Virginia Tech",
    "Alabama",
    "Butler",
    "St. Bonaventure/UCLA",
    "Murray State",
    "Marshall",
    "Stephen F. Austin",
    "Cal State-Fullerton",
    "Long Island-Brooklyn/Radford",
    "Kansas",
    "Duke",
    "Michigan State",
    "Auburn",
    "Clemson",
    "TCU",
    "Rhode Island",
    "Seton Hall",
    "NC State",
    "Oklahoma",
    "Arizona State/Syracuse",
    "New Mexico State",
    "Charleston",
    "Bucknell",
    "Iona",
    "Penn"
];

const GetTeamName = (teamId) => (
    teamId === 0 ? '______' : TeamNames[teamId-1]
)

export default GetTeamName